### ISSUE TITLE
in readme

### ISSUE THREAD

**Issue by srem1** [markqvist/Reticulum#216]
https://github.com/markqvist/reticulum
not exist
(rnode)

Currently, the following interfaces are supported:

Any Ethernet device
LoRa using [RNode](https://unsigned.io/projects/rnode/)
Packet Radio TNCs (with or without AX.25)
KISS-compatible hardware and software modems
Any device with a serial port
TCP over IP networks
UDP over IP networks
External programs via stdio or pipes
Custom hardware via stdio or pipes

**Comment by markqvist** [comment]
Thank you! You're really good at spotting these ;)
