### ISSUE TITLE
Request/Response does not support bytearray objects

### ISSUE THREAD

**Issue by acehoss** [markqvist/Reticulum#223]
If I try to send binary data in a request or response, usmgpack complains:

```
RNS.vendor.umsgpack.UnsupportedTypeException: unsupported type: <class 'bytearray'>
```

I'm working around this for now by base64 encoding the data.

**Comment by markqvist** [comment]
That is odd. That *should* work. If it doesn't I'll have it fixed in a hurry :)

**Comment by acehoss** [comment]
Currently my response generator returns an array with several elements, at least one of them being a `bytearray` object. 

The exception is raised at [Link.py:580](https://github.com/markqvist/Reticulum/blob/3706769c337c8f37eae11c9bea33269416967f5d/RNS/Link.py#L580):
```
packed_response = umsgpack.packb([request_id, response])
````

**Comment by acehoss** [comment]
Found the right solution here: umsgpack doesn't support `bytearray` objects, but it _does_ support `bytes` objects. Converting the `bytearray` to `bytes` before sending fixed the problem.

**Comment by markqvist** [comment]
I couldn't for the life of me reproduce this, until I remembered the specifics of *bytes* vs *bytearray* classes in Python. This happens because the `umsgpack` serialiser doesn't support the mutable *bytearray* type. It does support the *bytes* type however, so you can do this:

```
ba = bytearray([0x55, 0x45, 0xff])
b = bytes(ba)
```

**Comment by markqvist** [comment]
Haha, you beat me to it by about 15 seconds! Apparently we were looking at this exactly syncronously!
