### ISSUE TITLE
lo0 not ignored on NetBSD (AutoInterfaces)

### ISSUE THREAD

**Issue by gdt** [markqvist/Reticulum#237]
lo0 is not ignored on NetBSD but should be.

A larger issue is that it would be nice to have two structural changes in the default ignore list:
  - Have a list for all systems that includes lo0 (BSD-derived) and lo (Linux), to make things work better on unknown systems.
  - Rather than having `is_darwin()` etc. and variables per os, have a `osname()` method and a dictionary by os, so that it's easier to add support for new systems.

(But, it looks like on normal systems that mostly the odd interfaces that should be ignored don't have fe80, and aren't used anyway.)

**Comment by markqvist** [comment]
Agreed, I am looking into improving this for the next release.
