### ISSUE TITLE
AutoInterface discovery packets received by self

### ISSUE THREAD

**Issue by gdt** [markqvist/Reticulum#239]
Discovery packets from oneself are received.  This is a minor efficiency bug.  I think the cause is that there's a new socket for TX, rather than them being sent on the listening socket.  (It's also a minor efficiency bug to create and tear down a socket every second.)

It seems this is only noticeable because the transmit hash is wrong on NetBSD.

**Comment by markqvist** [comment]
This is intentional, AutoInterface uses these multicast "echoes" to asess link state, and to detect when to recover on link state changes, WiFi roaming and such. In some edge cases where adapters change MAC addresses on every reconnect, this behaviour is necessary.
