### ISSUE TITLE
Aspects definition in API/Manual

### ISSUE THREAD

**Issue by faragher** [markqvist/Reticulum#260]
I can't find good information on aspects in the manual or API (as related to Destination). I believe this, along with the appname, is the source of many of the problems I have with reception issues. At this point I can only guess it acts like a filter, but I can't find any reference to how they functionally work. Are they logical and? Logical or? Are they hardwired or arbitrary? If the appname really just a hard filter?

When possible, please either add this information to the manual or briefly answer the questions and I'll modify the manual (or work with the current revamp project) and make a pull request.

**Comment by markqvist** [comment]
Every destination is named by a `.`-separated list of aspects. The first is always the "application name" (use it to group all destination types from a single application, system or protocol together). All aspects under that can be defined in any way you like, but a complete destination name, eg. `myapplication.rpc.sensorstatus` is always unique and distinct from all others, and for each Identity coupled to it, forms a completely unique address on the network.

The manual definitely needs clarification in this area. Thanks for bringing it up.

**Comment by faragher** [comment]
I apologize, I'm still missing something fundamental.

Also, please understand I appreciate the effort of making an entire protocol and documenting it. I think I'm coming at it wrong.

Every endpoint (like a user on Sideband) has an identity. It has an asymmetric key and a hash based address. This is the key element, and packets are addressed to this hash.

Is the purpose of these aspects to allow for a single hash address to process multiple endpoints? Similar to Apache and subdomains, is this so Alice can send data to MyApplication.RPC.sensorstatus@hash and Bob can send to MyApplication.RPC.controlcode@hash and each is treated as a different destination by the receiver? I've forgotten if the delegates are by destination, but I guess that would make sense.

So, am I still misunderstanding, or is the parallel of subdomains on a web sever accurate, except instead of pointing to other directories (or even servers) this would point to a different destination, and thus different handling code?

**Comment by markqvist** [comment]
> Also, please understand I appreciate the effort of making an entire protocol and documenting it. I think I'm coming at it wrong.

No, I really meant that I appreciate your feedback, and thank you for bringing it up :) The documentation _is_ lacking there, and it needs improvement! It's been on my list forever, so it is a good reminder!

> Every endpoint (like a user on Sideband) has an identity. It has an asymmetric key and a hash based address. This is the key element, and packets are addressed to this hash.

This is kinda right, but misses a few details:

- One Identity has one set of Ed25519 (signing) and X25519 (encryption) public and private keys.
- An Identity does not in itself have any address on the network
- One Identity can be used to create *many* addresses (16-bytes, hash based like `6dcc2fc58e0f7d77af78d096bcd34abf`)
- To create an address (or *destination* in Reticulum terminology), you need both and *Identity* and a list of *aspects*.
- Therefore, it is the aspects that expand the Identity into multiple actual addresses on the network.
- By using different aspects, one Identity can control many different addresses (destinations) on the network. Or you can create new Identities for every destination you need, the choice is yours as the system designer.

Does it make more sense like that?

**Comment by faragher** [comment]
That may be the cause of the problem I had with the system returning an unexpected hash. That's problematic; I'll review my code and see if there's a better way to do it, but sending to a hash and getting a response with a different hash is unexpected.

So, when I load an identity from file, what am I loading? It returns a singular hexhash, and that seems to be how it's accessed when used to generate a destination. Is there something in request_path that makes it look like I'm using a hash when really it just obfuscates the aspects?

**Comment by markqvist** [comment]
> but sending to a hash and getting a response with a different hash is unexpected.

It is because you are getting the hash of the *identity*, which you will always know anyway. You can retrieve it just by knowing the destination hash. And you can also always get the destination hash for any set of aspects, if you know the identity.

> So, when I load an identity from file, what am I loading? It returns a singular hexhash, and that seems to be how it's accessed when used to generate a destination.

You are loading that specific identity. The hash you see from that is the hash of the identity. Any destination created from that identity will have their own, unique hashes, based on what aspects they have.

**Comment by faragher** [comment]
Is there then a good way to ensure that the incoming data is from the source specified, or is that out of scope? I understand you can sign the message, but I don't want to duplicate effort if there's a built-in system. 

Basically, I want to log that a message came from a known address hash. Or really just that the origin of the message is a trusted source. This can be over a link.

**Comment by markqvist** [comment]
If you have a link established, the initiator can use the `identify()` API call, which will reveal and authrnticate the initiator identity to the destination.
