### ISSUE TITLE
Storage cache exception in rnsd service

### ISSUE THREAD

**Issue by ThomasFreedman** [markqvist/Reticulum#322]
I started with 0.5.0, when I got this error I upgraded to 0.5.4 but same error occurs.
> [Notice] Started rnsd version 0.5.0 
> [Error] Error writing packet to cache
> [2023-06-04 11:58:06] [Notice] The contained exception was: [Errno 13] Permission denied: '/etc/reticulum/storage/cache/ae66013877678c37204cd03c835ed2d26b232a1669acb4419efdbb039ab12d23'

Using /etc/reticulum as service root, running under a user account not root account.

my RNS app running under a different account than rnsd service account.

This is the first time seeing this error. It occurred when I sent a request with a list of 1000 integers and one string of 46 characters. Regardless, all of it was received properly.

How to properly setup a system wide systemd service to handle multiple user accounts? Here are the permissions of the /etc/reticulum folder hierarchy:

/etc:
4 drwxr-xr-x 3 rtic rtic    4096 Jun  1 18:22 reticulum

$ ls -ls /etc/reticulum/
total 20
12 -rw-r--r-- 1 rtic rtic 9888 Apr 30 11:14 config
 4 -rw-r--r-- 1 rtic rtic   58 Jun  1 18:22 logfile
 4 drwxr-xr-x 5 rtic rtic 4096 Apr 28 20:08 storage
 
 $ ls -ls /etc/reticulum/storage/
total 23260
  168 drwxr-xr-x 2 rtic rtic   172032 Jun  4 12:05 cache
   28 -rw-r--r-- 1 rtic rtic    26653 Jun  4 12:05 destination_table
    4 drwxr-xr-x 2 rtic rtic     4096 Apr 28 20:07 identities
   68 -rw-r--r-- 1 rtic rtic    67418 Jun  4 12:05 known_destinations
22956 -rw-r--r-- 1 rtic rtic 23504273 Jun  4 12:05 packet_hashlist
    4 drwxr-xr-x 2 rtic rtic     4096 May 11 14:57 resources
    4 -rw-r--r-- 1 rtic rtic       64 Apr 28 20:07 transport_identity
   28 -rw-r--r-- 1 rtic rtic    25884 Jun  4 12:05 tunnels

**Comment by markqvist** [comment]
This is not an issue with Reticulum, but your filesystem permissions.

You just need to configure your groups and permissions so the relevant users (within a group, for example) has correct read and write access to the relevant directories.
