### ISSUE TITLE
Allow changing serial speed in rnodeconf.py to solve flashing issues

### ISSUE THREAD

**Issue by blackjack75** [markqvist/Reticulum#359]
Summary:
Please add a parameter to rnodeconf.py to specify serial speed for flashing firmware on LilyGo devices (and possibly others that could have this issue depending on hubs / cables).

There's already a ticket (closed) about flashing issues at high speed.
https://github.com/markqvist/Reticulum/issues/270

When flashing with "rnodeconf --autoinstall" the default speed is set to 921600 bauds. 
If I replace all ocurrences in 921600 to 115200 then flashing works just fine.

If I leave the normal speed then it will end with this error:
"A fatal error occurred: Invalid head of packet (0xE0)"

I would even suggest to add this parameter in an error message in case of failure.

**Comment by Erethon** [comment]
I've created a draft PR for this in #360. I didn't have the time to test it yet, but feel free to give it a try and report back here if it works. The argument for setting the baud rate when flashing the device is called `--baud-flash`.
